dist: bionic
sudo: false
notifications:
  email: false
language: node_js
node_js:
  - "10"
  - "8"
  - "6"
env:
  - GO_VERSION=1.9.5
  - GO_VERSION=1.10.1
  - GO_VERSION=1.12.4
cache: npm
install:
  - 'eval "$(gimme ${GO_VERSION})"'
  - 'go version'
  - 'npm install'
jobs:
  include:
    - stage: npm release
      node_js: "8"
      script: skip
      after_success:
        - npx semantic-release
branches:
  only:
    - master
