dist: xenial
sudo: false
notifications:
  email: false
language: node_js
node_js:
  - "10"
  - "8"
  - "6"
env:
  - GO_VERSION=1.10.8
  - GO_VERSION=1.13.3
  - GO_VERSION=1.14.0
cache:
  directories:
    - node_modules
install:
  - 'eval "$(gimme ${GO_VERSION})"'
  - 'go version'
  - 'npm install'
jobs:
  include:
    - stage: npm release
      node_js: "10"
      script: skip
      after_success:
        - npx semantic-release
branches:
  only:
    - master
